### ISSUE TITLE
CSV and/or JSON output

### ISSUE THREAD

**Issue by drj11** [RSE-Sheffield/sheffield-covid-19#7]
It doesn't do CSV or JSON output yet.

I suggest that for csv output:

    python ingest.py --csv myfile.csv

for JSON output:

    python ingest.py --json myfile.json

We should use

`argparse`, `json`, `csv` modules that are already built-in.

**Comment by drj11** [comment]
Aha, [apparently if you comment](https://github.blog/2019-06-25-assign-issues-to-issue-commenters/) here @midhun1998 I will then be able to assign you!

**Comment by midhun1998** [comment]
Thanks @drj11 .
